### ISSUE TITLE
List last N corgies minted

### ISSUE THREAD

**Issue by zahhar** [epam/corgis#128]
Tasks

- [x] BE - @acuarica  Investigate if `TreeMap` can be used to retrieve corgis by last inserted (it can't, see https://github.com/epam/corgis/issues/128#issuecomment-783308681)
- [x] BE - @acuarica  Otherwise, retrieve corgis using list implementation
- [x] FE - @ohexus  Update block title on homepage (see https://github.com/epam/corgis/issues/128#issuecomment-783562244) to **Last activity**. Card layout: https://codepen.io/zahhar/pen/rNWGmEM

**Comment by acuarica** [comment]
To keep the insertion order in the contract, we cannot use `TreeMap`[1] as discussed in our daily stand up. The `TreeMap` data structure retrieves its elements sorted by key (`Corgi` id), **not by insertion order**.

[1] https://docs.rs/near-sdk/2.0.1/near_sdk/collections/struct.TreeMap.html

**Comment by zahhar** [comment]
@acuarica - I'd like to suggest the way to solve the 'sorting dilemma' we discussed on the standup.

We could always sort by CreatedDate (abs date qhen Corgi was minted initially) across all endpoints. 
Difference is that:

-  on homepage we want to display Last N Corgis minted globally (where N can be 10 or 20, for example) - and they come as "Last minted"
- on user's page we want to display ALL corgies minted by him (prob we still limit it, say, 100 Corgies if this is required - open question) - and by default they also come sorted from the contract endpoint by "Last minted" date, BUT then FE sorts them properly by Modified_At date, so newly received Corgies will appear on top :)

**Comment by acuarica** [comment]
Thanks for the suggestion. The main issue with this solution is that it might show the global corgis and user owned corgis in different order. This might be confusing for the user. Let's take this scenario:

(the format `G: # | A: # | B: #` represents the corgis displayed Globally, for user A and user B respectively, the leftmost number represents first corgi the user see)

1. User A mints Corgi 1 `G: 1 | A: 1 | B: `
2. User B mints Corgi 2 `G: 2 1 | A: 1 | B: 2`
3. User A transfers Corgi 1 to User B `G: 2 1 | A: | B: 1 2`

In step 3, the global list didn’t change, however user B now sees the transferred Corgi 1 in the top of her list. That's why we might be better off having a consistent ordering across the contract. The homepage can be corgis with last activities instead.

**Comment by zahhar** [comment]
> The homepage can be corgis with last activities instead.

This looks elegant. In this case we only need to rename the block title on the homepage. Lets go with it.
