### ISSUE TITLE
Smartcontract error when retrieving list of corgies after deleting Corgie

### ISSUE THREAD

**Issue by zahhar** [epam/corgis#22]
To reproduce:

1. Create corgie
2. Delete corgie
3. Try to load list of corgies => Error occurs 

`Error: Querying call/luis.testnet/displayGlobalCorgis failed: wasm execution failed with error: FunctionCallError(HostError(GuestPanic {​​​​ panic_msg: "Element type must be nullable if array is holey, filename: \"~lib/array.ts\" line: 97 col: 39" }​​​​)).`

**Comment by acuarica** [comment]
From the `Array` AssemblyBook docs: [1]

> The Array API is very similar to JavaScript's (MDN (opens new window)), with the notable difference that one must make sure that there are no null values if T is a non-nullable reference type.

This is the root issue. The error is being thrown within the `Array` std lib:

https://github.com/AssemblyScript/assemblyscript/blob/7f4296d510c32a46e2811fa409d85cae5e74175a/std/assembly/array.ts#L96

I will fix the `displayGlobalCorgis` contract so that this error does not happen.

[1] https://www.assemblyscript.org/stdlib/array.html
